version: 2.1
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "15 21 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
jobs:
  test:
    docker:
      - image: 'circleci/node:latest-browsers'
    steps:
      - checkout
      - run:
          name: "Install Dependancies"
          command: |
            npm install
      - run:
          name: "Run tests"
          command: |
            npm run test
      - store_test_results:
          path: ./report/junit
