version: 2.1
workflows:
  version: 2.1
  build:
    triggers:
      - schedule:
          cron: "45 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
jobs:
  build:
    docker:
      - image: 'circleci/node:latest-browsers'
    steps:
      - checkout
      - run:
          name: "Revive Demo Users on Staging"
          command: |
            npm run revive-users
      - run:
          name: "Install Dependancies"
          command: |
            npm install
      - run:
          name: "Run tests"
          command: |
            npm run test
      - store_test_results:
          path: ./report/junit